[package]
name = "sirgovan"
version = "0.1.0"
edition = "2021"

[dependencies]
sirgovan-lib = { version = "*", path = "../lib"}
tracing-subscriber = "0.3.17"
tempfile = "3.10.1"
dotenvy = "0.15.7"
serenity = "0.12.0"
# console-subscriber = "*"

[dependencies.tokio]
version = "1.32.0"
features = ["macros", "signal", "rt-multi-thread"]
# features = ["macros", "signal", "rt-multi-thread", "full", "tracing"]

[dev-dependencies]
# For tokio-console
console-subscriber = "*"
tokio = {version = "1.32.0", features = ["macros", "signal", "rt-multi-thread", "full", "tracing"]}
