[package]
name = "sirgovan"
version = "0.1.0"
edition = "2021"

[dependencies]
sirgovan-lib = { version = "*", path = "../lib"}
dotenv = "0.15.0"
tracing-subscriber = "0.3.17"
# console-subscriber = "*"

[dependencies.tokio]
version = "1.32.0"
features = ["macros", "signal", "rt-multi-thread"]
# features = ["macros", "signal", "rt-multi-thread", "full", "tracing"]

[dev-dependencies]
# For tokio-console
console-subscriber = "*"
tokio = {version = "1.32.0", features = ["macros", "signal", "rt-multi-thread", "full", "tracing"]}