[workspace]
members = ["macros", "executable", "lib"]
default-members = ["executable"]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
opt-level = 3
strip = true
lto = true
panic = "abort"