[workspace]
resolver = "2"
members = ["macros", "bin", "lib"]
default-members = ["bin"]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
opt-level = 3
strip = true
lto = true
panic = "abort"
