[package]
name = "sirgovan-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ['full', 'extra-traits'] }
quote = "*"
proc-macro2 = "*"
proc-macro-error = "1.0.4"
