name: Rust build

on: [ push, pull_request ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target[1] }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ ['aarch64-unknown-linux-gnu', 'ARM'], ['x86_64-unknown-linux-gnu', 'x86'] ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        target: ${{ matrix.target[0] }}
    - name: Build target
      run: cargo build --verbose --release --target ${{ matrix.target[0] }} 