name: Rust CI

on: [ push, pull_request ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target[1] }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ ['aarch64-unknown-linux-gnu', 'ARM'], ['x86_64-unknown-linux-gnu', 'x86'] ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ matrix.target[0] }}
    - name: Build target
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --release --target ${{ matrix.target[0] }}